"""
CARLA Scenario Script — Generated by ScenarioGen
Scenario ID : 5a5831cd
Description : a pedestrian jaywalks at night in rain
Road Type   : residential
Weather     : rain  |  Time: night
Duration    : 10.0s
"""

import carla
import time
import math


def run_scenario(host='localhost', port=2000):
    client = carla.Client(host, port)
    client.set_timeout(10.0)
    world = client.get_world()
    blueprint_library = world.get_blueprint_library()
    spectator = world.get_spectator()

    # ── Weather & time ──────────────────────────────────────────
    weather = carla.WeatherParameters.HardRainNoon
    weather.sun_altitude_angle = -30.0
    weather.precipitation = 80.0
    weather.fog_density = 20.0
    world.set_weather(weather)

    # ── Ego vehicle ─────────────────────────────────────────────
    ego_bp = blueprint_library.find('vehicle.tesla.model3')
    ego_bp.set_attribute('role_name', 'ego')
    ego_transform = carla.Transform(
        carla.Location(x=0.0, y=0.0, z=0.5),
        carla.Rotation(yaw=90.0)
    )
    ego = world.spawn_actor(ego_bp, ego_transform)
    ego.set_target_velocity(carla.Vector3D(
        x=0.0, y=20.0, z=0.0))

    actors = [ego]

    # ── Scenario actors ──────────────────────────────────────────

    # Actor 1: pedestrian — jaywalking
    bp_0 = blueprint_library.find('walker.pedestrian.0001')
    transform_0 = carla.Transform(
        carla.Location(x=15.0, y=15.0, z=0.5),
        carla.Rotation(yaw=90.0)
    )
    actor_0 = world.try_spawn_actor(bp_0, transform_0)
    if actor_0:
        walker_control = carla.WalkerControl()
        walker_control.speed = 2.5
        walker_control.direction = carla.Vector3D(x=0.00, y=2.50, z=0.0)
        actor_0.apply_control(walker_control)
        actors.append(actor_0)

    # ── Run scenario ────────────────────────────────────────────
    print(f'Scenario 5a5831cd running for 10s...')
    time.sleep(10)

    # ── Cleanup ─────────────────────────────────────────────────
    print('Cleaning up actors...')
    for a in actors:
        a.destroy()
    print('Done.')


if __name__ == '__main__':
    run_scenario()