"""
Export ScenarioConfig to CARLA-compatible Python script and JSON config.
CARLA uses Python scripts with its own API to spawn actors and set weather.
"""

import json
import math
import os
from src.schema import ScenarioConfig

CARLA_WEATHER = {
    "clear": "carla.WeatherParameters.ClearNoon",
    "rain":  "carla.WeatherParameters.HardRainNoon",
    "fog":   "carla.WeatherParameters.SoftRainSunset",
    "snow":  "carla.WeatherParameters.WetCloudyNoon",
}

CARLA_BLUEPRINT = {
    "vehicle":    "vehicle.tesla.model3",
    "motorcycle": "vehicle.kawasaki.ninja",
    "cyclist":    "vehicle.bh.crossbike",
    "pedestrian": "walker.pedestrian.0001",
}

CARLA_TIME = {
    "day":   (12, 0),
    "dusk":  (18, 30),
    "night": (22, 0),
}

ROAD_TO_MAP = {
    "intersection": "Town03",
    "highway":      "Town04",
    "residential":  "Town01",
    "parking_lot":  "Town05",
}


def heading_to_velocity(heading_deg, speed):
    rad = math.radians(heading_deg)
    return math.cos(rad) * speed, math.sin(rad) * speed

def sun_angle(time_of_day):
    return {"day": 60.0, "dusk": 5.0, "night": -30.0}.get(time_of_day, 60.0)

def precipitation(weather):
    return {"clear": 0.0, "rain": 80.0, "fog": 10.0, "snow": 60.0}.get(weather, 0.0)

def fog_density(weather):
    return {"clear": 0.0, "rain": 20.0, "fog": 80.0, "snow": 30.0}.get(weather, 0.0)


def export_to_carla(config, output_path=None):
    """
    Generate a CARLA-compatible Python scenario script from a ScenarioConfig.

    Args:
        config: validated ScenarioConfig instance
        output_path: path to save .py file (default: examples/<scenario_id>_carla.py)

    Returns:
        path to the saved file
    """
    if output_path is None:
        os.makedirs("examples", exist_ok=True)
        output_path = "examples/" + config.scenario_id + "_carla.py"

    env = config.environment
    hour, minute = CARLA_TIME.get(env.time_of_day, (12, 0))
    weather = CARLA_WEATHER.get(env.weather, "carla.WeatherParameters.ClearNoon")

    lines = [
        '"""',
        "CARLA Scenario Script generated by ScenarioGen",
        "Scenario ID : " + config.scenario_id,
        "Description : " + config.description,
        "Road Type   : " + env.road_type,
        "Weather     : " + env.weather + "  |  Time: " + env.time_of_day,
        "Duration    : " + str(config.duration_seconds) + "s",
        '"""',
        "",
        "import carla",
        "import time",
        "import math",
        "",
        "",
        "def run_scenario(host='localhost', port=2000):",
        "    client = carla.Client(host, port)",
        "    client.set_timeout(10.0)",
        "    world = client.get_world()",
        "    blueprint_library = world.get_blueprint_library()",
        "",
        "    weather = " + weather,
        "    weather.sun_altitude_angle = " + str(sun_angle(env.time_of_day)),
        "    weather.precipitation = " + str(precipitation(env.weather)),
        "    weather.fog_density = " + str(fog_density(env.weather)),
        "    world.set_weather(weather)",
        "",
        "    ego_bp = blueprint_library.find('vehicle.tesla.model3')",
        "    ego_bp.set_attribute('role_name', 'ego')",
        "    ego_transform = carla.Transform(",
        "        carla.Location(x=0.0, y=0.0, z=0.5),",
        "        carla.Rotation(yaw=90.0)",
        "    )",
        "    ego = world.spawn_actor(ego_bp, ego_transform)",
        "    ego.set_target_velocity(carla.Vector3D(",
        "        x=0.0, y=" + str(config.ego_vehicle_speed_mps) + ", z=0.0))",
        "",
        "    actors = [ego]",
        "",
    ]

    for i, actor in enumerate(config.actors):
        bp_key = CARLA_BLUEPRINT.get(actor.actor_type, "vehicle.tesla.model3")
        x, y = actor.start_position
        heading = actor.heading_degrees
        is_walker = actor.actor_type == "pedestrian"
        vx, vy = heading_to_velocity(heading, actor.speed_mps)

        lines += [
            "    # Actor " + str(i + 1) + ": " + actor.actor_type + " - " + actor.behavior,
            "    bp_" + str(i) + " = blueprint_library.find('" + bp_key + "')",
        ]

        if not is_walker:
            lines += [
                "    transform_" + str(i) + " = carla.Transform(",
                "        carla.Location(x=" + str(x) + ", y=" + str(y) + ", z=0.5),",
                "        carla.Rotation(yaw=" + str(heading) + ")",
                "    )",
                "    actor_" + str(i) + " = world.spawn_actor(bp_" + str(i) + ", transform_" + str(i) + ")",
                "    actor_" + str(i) + ".set_target_velocity(carla.Vector3D(x=" + str(round(vx, 2)) + ", y=" + str(round(vy, 2)) + ", z=0.0))",
                "    actors.append(actor_" + str(i) + ")",
                "",
            ]
        else:
            lines += [
                "    transform_" + str(i) + " = carla.Transform(",
                "        carla.Location(x=" + str(x) + ", y=" + str(y) + ", z=0.5),",
                "        carla.Rotation(yaw=" + str(heading) + ")",
                "    )",
                "    actor_" + str(i) + " = world.try_spawn_actor(bp_" + str(i) + ", transform_" + str(i) + ")",
                "    if actor_" + str(i) + ":",
                "        walker_control = carla.WalkerControl()",
                "        walker_control.speed = " + str(actor.speed_mps),
                "        walker_control.direction = carla.Vector3D(x=" + str(round(vx, 2)) + ", y=" + str(round(vy, 2)) + ", z=0.0)",
                "        actor_" + str(i) + ".apply_control(walker_control)",
                "        actors.append(actor_" + str(i) + ")",
                "",
            ]

    lines += [
        "    print('Scenario " + config.scenario_id + " running for " + str(int(config.duration_seconds)) + "s...')",
        "    time.sleep(" + str(int(config.duration_seconds)) + ")",
        "",
        "    print('Cleaning up actors...')",
        "    for a in actors:",
        "        a.destroy()",
        "    print('Done.')",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_scenario()",
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output_path


def export_to_carla_json(config, output_path=None):
    """
    Export a lightweight CARLA-compatible JSON config.
    Useful for tools that read scenario descriptors directly.
    """
    if output_path is None:
        os.makedirs("examples", exist_ok=True)
        output_path = "examples/" + config.scenario_id + "_carla.json"

    hour, minute = CARLA_TIME.get(config.environment.time_of_day, (12, 0))

    carla_config = {
        "scenario_id": config.scenario_id,
        "description": config.description,
        "map": ROAD_TO_MAP.get(config.environment.road_type, "Town03"),
        "duration_seconds": config.duration_seconds,
        "weather": {
            "preset": CARLA_WEATHER.get(config.environment.weather),
            "sun_altitude_angle": sun_angle(config.environment.time_of_day),
            "precipitation": precipitation(config.environment.weather),
            "fog_density": fog_density(config.environment.weather),
        },
        "time_of_day": {"hour": hour, "minute": minute},
        "ego_vehicle": {
            "blueprint": "vehicle.tesla.model3",
            "spawn": {"x": 0.0, "y": 0.0, "z": 0.5, "yaw": 90.0},
            "speed_mps": config.ego_vehicle_speed_mps,
        },
        "actors": [
            {
                "id": "actor_" + str(i),
                "blueprint": CARLA_BLUEPRINT.get(a.actor_type),
                "actor_type": a.actor_type,
                "behavior": a.behavior,
                "spawn": {
                    "x": a.start_position[0],
                    "y": a.start_position[1],
                    "z": 0.5,
                    "yaw": a.heading_degrees,
                },
                "speed_mps": a.speed_mps,
            }
            for i, a in enumerate(config.actors)
        ],
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(carla_config, f, indent=2)

    return output_path