"""
ScenarioGen — Export ScenarioConfig to CARLA-compatible Python script.

CARLA uses Python scripts with its own API to spawn actors and set weather.
This exporter generates a ready-to-run CARLA scenario script.
"""

import json
import os
from src.schema import ScenarioConfig

# ── CARLA mappings ────────────────────────────────────────────────────────────

CARLA_WEATHER = {
    "clear": "carla.WeatherParameters.ClearNoon",
    "rain":  "carla.WeatherParameters.HardRainNoon",
    "fog":   "carla.WeatherParameters.SoftRainSunset",
    "snow":  "carla.WeatherParameters.WetCloudyNoon",
}

CARLA_BLUEPRINT = {
    "vehicle":     "vehicle.tesla.model3",
    "motorcycle":  "vehicle.kawasaki.ninja",
    "cyclist":     "vehicle.bh.crossbike",
    "pedestrian":  "walker.pedestrian.0001",
}

CARLA_TIME = {
    "day":  (12, 0),   # (hour, minute)
    "dusk": (18, 30),
    "night": (22, 0),
}


# ── Exporter ──────────────────────────────────────────────────────────────────

def export_to_carla(config: ScenarioConfig, output_path: str = None) -> str:
    """
    Generate a CARLA-compatible Python scenario script from a ScenarioConfig.

    Args:
        config: validated ScenarioConfig instance
        output_path: path to save .py file (default: examples/<scenario_id>_carla.py)

    Returns:
        path to saved file
    """
    if output_path is None:
        os.makedirs("examples", exist_ok=True)
        output_path = f"examples/{config.scenario_id}_carla.py"

    env = config.environment
    hour, minute = CARLA_TIME.get(env.time_of_day, (12, 0))
    weather = CARLA_WEATHER.get(env.weather, "carla.WeatherParameters.ClearNoon")

    lines = [
        '"""',
        f'CARLA Scenario Script — Generated by ScenarioGen',
        f'Scenario ID : {config.scenario_id}',
        f'Description : {config.description}',
        f'Road Type   : {env.road_type}',
        f'Weather     : {env.weather}  |  Time: {env.time_of_day}',
        f'Duration    : {config.duration_seconds}s',
        '"""',
        "",
        "import carla",
        "import time",
        "import math",
        "",
        "",
        "def run_scenario(host='localhost', port=2000):",
        "    client = carla.Client(host, port)",
        "    client.set_timeout(10.0)",
        "    world = client.get_world()",
        "    blueprint_library = world.get_blueprint_library()",
        "    spectator = world.get_spectator()",
        "",
        f"    # ── Weather & time ──────────────────────────────────────────",
        f"    weather = {weather}",
        f"    weather.sun_altitude_angle = {_sun_angle(env.time_of_day)}",
        f"    weather.precipitation = {_precipitation(env.weather)}",
        f"    weather.fog_density = {_fog(env.weather)}",
        "    world.set_weather(weather)",
        "",
        f"    # ── Ego vehicle ─────────────────────────────────────────────",
        f"    ego_bp = blueprint_library.find('vehicle.tesla.model3')",
        f"    ego_bp.set_attribute('role_name', 'ego')",
        f"    ego_transform = carla.Transform(",
        f"        carla.Location(x=0.0, y=0.0, z=0.5),",
        f"        carla.Rotation(yaw=90.0)",
        f"    )",
        f"    ego = world.spawn_actor(ego_bp, ego_transform)",
        f"    ego.set_target_velocity(carla.Vector3D(",
        f"        x=0.0, y={config.ego_vehicle_speed_mps:.1f}, z=0.0))",
        "",
        "    actors = [ego]",
        "",
        "    # ── Scenario actors ──────────────────────────────────────────",
    ]

    for i, actor in enumerate(config.actors):
        bp_key = CARLA_BLUEPRINT.get(actor.actor_type, "vehicle.tesla.model3")
        x, y = actor.start_position
        heading = actor.heading_degrees
        is_walker = actor.actor_type == "pedestrian"

        lines += [
            f"",
            f"    # Actor {i+1}: {actor.actor_type} — {actor.behavior}",
            f"    bp_{i} = blueprint_library.find('{bp_key}')",
        ]

        if not is_walker:
            vx, vy = _heading_to_velocity(heading, actor.speed_mps)
            lines += [
                f"    transform_{i} = carla.Transform(",
                f"        carla.Location(x={x:.1f}, y={y:.1f}, z=0.5),",
                f"        carla.Rotation(yaw={heading:.1f})",
                f"    )",
                f"    actor_{i} = world.spawn_actor(bp_{i}, transform_{i})",
                f"    actor_{i}.set_target_velocity(carla.Vector3D(x={vx:.2f}, y={vy:.2f}, z=0.0))",
                f"    actors.append(actor_{i})",
            ]
        else:
            vx, vy = _heading_to_velocity(heading, actor.speed_mps)
            lines += [
                f"    transform_{i} = carla.Transform(",
                f"        carla.Location(x={x:.1f}, y={y:.1f}, z=0.5),",
                f"        carla.Rotation(yaw={heading:.1f})",
                f"    )",
                f"    actor_{i} = world.try_spawn_actor(bp_{i}, transform_{i})",
                f"    if actor_{i}:",
                f"        walker_control = carla.WalkerControl()",
                f"        walker_control.speed = {actor.speed_mps:.1f}",
                f"        walker_control.direction = carla.Vector3D(x={vx:.2f}, y={vy:.2f}, z=0.0)",
                f"        actor_{i}.apply_control(walker_control)",
                f"        actors.append(actor_{i})",
            ]

    lines += [
        "",
        f"    # ── Run scenario ────────────────────────────────────────────",
        f"    print(f'Scenario {config.scenario_id} running for {config.duration_seconds:.0f}s...')",
        f"    time.sleep({config.duration_seconds:.0f})",
        "",
        "    # ── Cleanup ─────────────────────────────────────────────────",
        "    print('Cleaning up actors...')",
        "    for a in actors:",
        "        a.destroy()",
        "    print('Done.')",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_scenario()",
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output_path


def export_to_carla_json(config: ScenarioConfig, output_path: str = None) -> str:
    """
    Export a lightweight CARLA-compatible JSON config (no Python required).
    Useful for tools that read scenario descriptors directly.
    """
    if output_path is None:
        os.makedirs("examples", exist_ok=True)
        output_path = f"examples/{config.scenario_id}_carla.json"

    hour, minute = CARLA_TIME.get(config.environment.time_of_day, (12, 0))

    carla_config = {
        "scenario_id": config.scenario_id,
        "description": config.description,
        "map": _road_to_map(config.environment.road_type),
        "duration_seconds": config.duration_seconds,
        "weather": {
            "preset": CARLA_WEATHER.get(config.environment.weather),
            "sun_altitude_angle": _sun_angle(config.environment.time_of_day),
            "precipitation": _precipitation(config.environment.weather),
            "fog_density": _fog(config.environment.weather),
        },
        "time_of_day": {"hour": hour, "minute": minute},
        "ego_vehicle": {
            "blueprint": "vehicle.tesla.model3",
            "spawn": {"x": 0.0, "y": 0.0, "z": 0.5, "yaw": 90.0},
            "speed_mps": config.ego_vehicle_speed_mps,
        },
        "actors": [
            {
                "id": f"actor_{i}",
                "blueprint": CARLA_BLUEPRINT.get(a.actor_type),
                "actor_type": a.actor_type,
                "behavior": a.behavior,
                "spawn": {
                    "x": a.start_position[0],
                    "y": a.start_position[1],
                    "z": 0.5,
                    "yaw": a.heading_degrees,
                },
                "speed_mps": a.speed_mps,
            }
            for i, a in enumerate(config.actors)
        ],
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(carla_config, f, indent=2)

    return output_path


# ── Helpers ───────────────────────────────────────────────────────────────────

def _heading_to_velocity(heading_deg: float, speed: float) -> tuple[float, float]:
    import math
    rad = math.radians(heading_deg)
    return math.cos(rad) * speed, math.sin(rad) * speed

def _sun_angle(time_of_day: str) -> float:
    return {"day": 60.0, "dusk": 5.0, "night": -30.0}.get(time_of_day, 60.0)

def _precipitation(weather: str) -> float:
    return {"clear": 0.0, "rain": 80.0, "fog": 10.0, "snow": 60.0}.get(weather, 0.0)

def _fog(weather: str) -> float:
    return {"clear": 0.0, "rain": 20.0, "fog": 80.0, "snow": 30.0}.get(weather, 0.0)

def _road_to_map(road_type: str) -> str:
    return {
        "intersection": "Town03",
        "highway":      "Town04",
        "residential":  "Town01",
        "parking_lot":  "Town05",
    }.get(road_type, "Town03")